CREATE TABLE checkout_lock_idempotency_keys (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) NOT NULL,
    owner_type VARCHAR(255) NOT NULL,
    user_id BIGINT,
    guest_email VARCHAR(255),
    request_fingerprint VARCHAR(255) NOT NULL,
    showtime_id BIGINT NOT NULL,
    session_id VARCHAR(255),
    expires_at TIMESTAMP NOT NULL,
    locked_seat_ids TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_checkout_lock_idempotency_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT fk_checkout_lock_idempotency_showtime
        FOREIGN KEY (showtime_id) REFERENCES showtime (id),

    CONSTRAINT chk_checkout_lock_idempotency_owner
        CHECK (
            (owner_type = 'USER' AND user_id IS NOT NULL AND guest_email IS NULL)
            OR
            (owner_type = 'GUEST' AND user_id IS NULL AND guest_email IS NOT NULL)
        )
);

CREATE UNIQUE INDEX uk_checkout_lock_idempotency_user_key
    ON checkout_lock_idempotency_keys (user_id, idempotency_key)
    WHERE owner_type = 'USER'
    AND user_id IS NOT NULL;

CREATE UNIQUE INDEX uk_checkout_lock_idempotency_guest_key
    ON checkout_lock_idempotency_keys (guest_email, idempotency_key)
    WHERE owner_type = 'GUEST'
    AND guest_email IS NOT NULL;

CREATE INDEX idx_checkout_lock_idempotency_expires_at
    ON checkout_lock_idempotency_keys (expires_at);
