CREATE TABLE processed_outbox_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL,
    consumer_name VARCHAR(100) NOT NULL,
    processed_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_processed_outbox_events_event_consumer UNIQUE (event_id, consumer_name),
    CONSTRAINT fk_processed_outbox_events_event
        FOREIGN KEY (event_id) REFERENCES outbox_events (id)
);

CREATE INDEX idx_processed_outbox_events_consumer_name
    ON processed_outbox_events (consumer_name);
