ALTER TABLE movie
    ADD COLUMN active BOOLEAN NOT NULL DEFAULT TRUE,
    ADD COLUMN created_at TIMESTAMP,
    ADD COLUMN updated_at TIMESTAMP;

UPDATE movie
SET created_at = COALESCE(created_at, CURRENT_TIMESTAMP),
    updated_at = COALESCE(updated_at, CURRENT_TIMESTAMP),
    active = COALESCE(active, TRUE);

ALTER TABLE movie
    ALTER COLUMN created_at SET NOT NULL,
    ALTER COLUMN updated_at SET NOT NULL;

CREATE TABLE screen_layout_versions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL,
    version_number INTEGER NOT NULL,
    active BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_screen_layout_versions_screen FOREIGN KEY (screen_id) REFERENCES screen (id),
    CONSTRAINT uk_screen_layout_versions_screen_version UNIQUE (screen_id, version_number)
);

INSERT INTO screen_layout_versions (screen_id, version_number, active, created_at, updated_at)
SELECT id, 1, TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
FROM screen;

ALTER TABLE seat
    ADD COLUMN layout_version_id BIGINT;

UPDATE seat s
SET layout_version_id = slv.id
FROM screen_layout_versions slv
WHERE slv.screen_id = s.screen_id
  AND slv.version_number = 1;

ALTER TABLE seat
    ADD CONSTRAINT fk_seat_layout_version FOREIGN KEY (layout_version_id) REFERENCES screen_layout_versions (id);

ALTER TABLE showtime
    ADD COLUMN layout_version_id BIGINT;

UPDATE showtime st
SET layout_version_id = slv.id
FROM screen_layout_versions slv
WHERE slv.screen_id = st.screen_id
  AND slv.version_number = 1;

ALTER TABLE showtime
    ADD CONSTRAINT fk_showtime_layout_version FOREIGN KEY (layout_version_id) REFERENCES screen_layout_versions (id);

ALTER TABLE screen
    ADD COLUMN current_layout_version_id BIGINT;

UPDATE screen sc
SET current_layout_version_id = slv.id
FROM screen_layout_versions slv
WHERE slv.screen_id = sc.id
  AND slv.version_number = 1;

ALTER TABLE screen
    ADD CONSTRAINT fk_screen_current_layout_version FOREIGN KEY (current_layout_version_id) REFERENCES screen_layout_versions (id);

CREATE INDEX idx_movie_active ON movie (active);
CREATE INDEX idx_screen_layout_versions_screen_active ON screen_layout_versions (screen_id, active);
CREATE INDEX idx_seat_layout_version_active ON seat (layout_version_id, active);
CREATE INDEX idx_showtime_layout_version_id ON showtime (layout_version_id);
CREATE INDEX idx_showtime_start_movie_screen ON showtime (start_time, movie_id, screen_id);
CREATE INDEX idx_reservation_status_payment_booking_time ON reservation (status, payment_status, booking_time);
CREATE INDEX idx_reservation_cancelled_at_status ON reservation (cancelled_at, status);
CREATE INDEX idx_checkout_sessions_created_status ON checkout_sessions (created_at, status);
CREATE INDEX idx_checkout_sessions_showtime_created ON checkout_sessions (showtime_id, created_at);
