CREATE TABLE programme_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    starts_on DATE NOT NULL,
    ends_on DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_programme_entry_movie FOREIGN KEY (movie_id) REFERENCES movie (id),
    CONSTRAINT ck_programme_entry_dates CHECK (ends_on = starts_on + 6),
    CONSTRAINT uk_programme_entry_movie_week UNIQUE (movie_id, starts_on),
    CONSTRAINT uk_programme_entry_id_movie UNIQUE (id, movie_id)
);

CREATE INDEX idx_programme_entry_starts_on ON programme_entry (starts_on);
CREATE INDEX idx_programme_entry_movie_id ON programme_entry (movie_id);

ALTER TABLE showtime
    ADD COLUMN programme_entry_id BIGINT,
    ADD CONSTRAINT fk_showtime_programme_entry_movie
        FOREIGN KEY (programme_entry_id, movie_id) REFERENCES programme_entry (id, movie_id);

CREATE INDEX idx_showtime_programme_entry_id ON showtime (programme_entry_id);
