CREATE TABLE movie (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255),
    director VARCHAR(255)
);

CREATE TABLE theatres (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    state VARCHAR(255) NOT NULL,
    country VARCHAR(255) NOT NULL,
    postal_code VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    total_screens INTEGER,
    total_seats INTEGER,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    active BOOLEAN NOT NULL
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    phone_number VARCHAR(255),
    role VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT uk_users_phone_number UNIQUE (phone_number)
);

CREATE TABLE screen (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    theatre_id BIGINT NOT NULL,
    total_seats INTEGER NOT NULL,
    screen_type VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_screen_theatre FOREIGN KEY (theatre_id) REFERENCES theatres (id)
);

CREATE TABLE seat (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    screen_id BIGINT NOT NULL,
    row_label VARCHAR(255) NOT NULL,
    seat_number INTEGER NOT NULL,
    seat_type VARCHAR(255) NOT NULL,
    base_price NUMERIC(38, 2) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    active BOOLEAN NOT NULL,
    CONSTRAINT fk_seat_screen FOREIGN KEY (screen_id) REFERENCES screen (id)
);

CREATE TABLE showtime (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    movie_id BIGINT NOT NULL,
    screen_id BIGINT NOT NULL,
    start_time TIMESTAMP NOT NULL,
    end_time TIMESTAMP NOT NULL,
    base_price NUMERIC(38, 2) NOT NULL,
    available_seats INTEGER NOT NULL,
    total_seats INTEGER NOT NULL,
    status VARCHAR(255),
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT fk_showtime_movie FOREIGN KEY (movie_id) REFERENCES movie (id),
    CONSTRAINT fk_showtime_screen FOREIGN KEY (screen_id) REFERENCES screen (id)
);

CREATE TABLE reservation (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    booking_reference VARCHAR(255) NOT NULL,
    number_of_seats INTEGER NOT NULL,
    total_price NUMERIC(38, 2) NOT NULL,
    status VARCHAR(255) NOT NULL,
    payment_status VARCHAR(255),
    booking_time TIMESTAMP NOT NULL,
    cancelled_at TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT uk_reservation_booking_reference UNIQUE (booking_reference),
    CONSTRAINT fk_reservation_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_reservation_showtime FOREIGN KEY (showtime_id) REFERENCES showtime (id)
);

CREATE TABLE reservation_seats (
    reservation_id BIGINT NOT NULL,
    seat_id BIGINT NOT NULL,
    PRIMARY KEY (reservation_id, seat_id),
    CONSTRAINT fk_reservation_seats_reservation FOREIGN KEY (reservation_id) REFERENCES reservation (id),
    CONSTRAINT fk_reservation_seats_seat FOREIGN KEY (seat_id) REFERENCES seat (id)
);

CREATE TABLE seat_locks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    seat_id BIGINT NOT NULL,
    showtime_id BIGINT NOT NULL,
    user_id BIGINT,
    session_id VARCHAR(255),
    locked_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    status VARCHAR(255) NOT NULL,
    CONSTRAINT fk_seat_locks_seat FOREIGN KEY (seat_id) REFERENCES seat (id),
    CONSTRAINT fk_seat_locks_showtime FOREIGN KEY (showtime_id) REFERENCES showtime (id),
    CONSTRAINT fk_seat_locks_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX idx_screen_theatre_id ON screen (theatre_id);
CREATE INDEX idx_seat_screen_id ON seat (screen_id);
CREATE INDEX idx_showtime_movie_id ON showtime (movie_id);
CREATE INDEX idx_showtime_screen_id ON showtime (screen_id);
CREATE INDEX idx_reservation_user_id ON reservation (user_id);
CREATE INDEX idx_reservation_showtime_id ON reservation (showtime_id);
CREATE INDEX idx_reservation_seats_seat_id ON reservation_seats (seat_id);
CREATE INDEX idx_seat_locks_seat_id ON seat_locks (seat_id);
CREATE INDEX idx_seat_locks_showtime_id ON seat_locks (showtime_id);
CREATE INDEX idx_seat_locks_user_id ON seat_locks (user_id);
