CREATE TABLE checkout_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    checkout_reference VARCHAR(255) NOT NULL,
    showtime_id BIGINT NOT NULL,
    user_id BIGINT,
    guest_email VARCHAR(255),
    guest_session_id VARCHAR(255),
    items_snapshot_json TEXT NOT NULL,
    total_amount NUMERIC(10, 2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    status VARCHAR(255) NOT NULL,
    stripe_checkout_session_id VARCHAR(255),
    stripe_payment_intent_id VARCHAR(255),
    stripe_customer_email VARCHAR(255),
    reservation_id BIGINT,
    expires_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    failed_at TIMESTAMP,
    cancelled_at TIMESTAMP,

    CONSTRAINT uk_checkout_sessions_checkout_reference UNIQUE (checkout_reference),
    CONSTRAINT uk_checkout_sessions_stripe_checkout_session_id UNIQUE (stripe_checkout_session_id),

    CONSTRAINT fk_checkout_sessions_showtime
        FOREIGN KEY (showtime_id) REFERENCES showtime (id),

    CONSTRAINT fk_checkout_sessions_user
        FOREIGN KEY (user_id) REFERENCES users (id),

    CONSTRAINT fk_checkout_sessions_reservation
        FOREIGN KEY (reservation_id) REFERENCES reservation (id),

    CONSTRAINT chk_checkout_sessions_owner
        CHECK (
            (user_id IS NOT NULL AND guest_email IS NULL AND guest_session_id IS NULL)
            OR
            (user_id IS NULL AND guest_email IS NOT NULL AND guest_session_id IS NOT NULL)
        )
);

CREATE INDEX idx_checkout_sessions_showtime_id
    ON checkout_sessions (showtime_id);

CREATE INDEX idx_checkout_sessions_user_id
    ON checkout_sessions (user_id);

CREATE INDEX idx_checkout_sessions_guest_identity
    ON checkout_sessions (guest_email, guest_session_id);

CREATE INDEX idx_checkout_sessions_status_expires_at
    ON checkout_sessions (status, expires_at);

CREATE INDEX idx_checkout_sessions_reservation_id
    ON checkout_sessions (reservation_id);
